# Generated by Django 4.1.7 on 2025-04-01 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konfiguration',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ort', models.CharField(max_length=255, unique=True, verbose_name='Ort')),
                ('plz', models.CharField(max_length=5, verbose_name='PLZ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
