# Generated by Django 4.1.7 on 2025-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FMD', 'FMD'), ('VERWALTUNG', 'Verwaltung'), ('ATEMSCHUTZ', 'Atemschutz'), ('MEMBER', 'Mitglied')], default='MEMBER', max_length=20, verbose_name='Benutzerrolle'),
        ),
    ]
