# Generated by Django 4.1.7 on 2025-04-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
