#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /app/manage.py migrate --noinput

exec /usr/local/bin/gunicorn rest_api.wsgi:application \
    --bind 0.0.0.0:9999 \
    --chdir=/app
